spring.application.name=portfolio-service
app.aws.s3.resume-bucket=abhishek-portfolio-bucket-2026

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=12MB

app.aws.s3.profile-image-bucket=abhishek-portfolio-profile-images-2026